apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "b3-site.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "b3-site.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "b3-site.name" . }}
    spec:
      containers:
        - name: b3-site
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}